version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo-shop
    ports:
      - 8080:8080

  mongo-shop:
    image: mongo:latest
    environment:
      MONGO_HOST: mongodb://localhost
      MONGO_PORT: 27017
      MONGO_DATABASE_NAME: app
#      MONGO_INITDB_ROOT_USERNAME: app
#      MONGO_INITDB_ROOT_PASSWORD: app
    volumes:
      - mongodata:/var/lib/mongodb/data
    ports:
      - 27017:27017

volumes:
  mongodata:
